### PR TITLE
Add Great Books of the Western World collection

### PR DESCRIPTION
**Pull request by bentley**
[Wikipedia](https://en.wikipedia.org/wiki/Great_Books_of_the_Western_World):

> *Great Books of the Western World* is a series of books originally published in the United States in 1952, by Encyclopædia Britannica, Inc., to present the Great Books in a 54-volume set.

If this is okay, I plan to do the same for the rest. Currently 51 of our works would qualify:

homer/the-iliad/william-cullen-bryant  
homer/the-odyssey/william-cullen-bryant  
aristotle/nicomachean-ethics/f-h-peters  
marcus-aurelius/meditations/george-long  
virgil/the-aeneid/john-dryden  
dante-alighieri/the-divine-comedy/henry-wadsworth-longfellow  
niccolo-machiavelli/the-prince/w-k-marriott  
william-shakespeare/henry-vi-part-i  
william-shakespeare/henry-vi-part-ii  
william-shakespeare/henry-vi-part-iii  
william-shakespeare/the-comedy-of-errors  
william-shakespeare/romeo-and-juliet  
william-shakespeare/a-midsummer-nights-dream  
william-shakespeare/henry-iv-part-i  
william-shakespeare/henry-iv-part-ii  
william-shakespeare/much-ado-about-nothing  
william-shakespeare/henry-v  
william-shakespeare/julius-caesar  
william-shakespeare/as-you-like-it  
william-shakespeare/twelfth-night  
william-shakespeare/hamlet  
william-shakespeare/the-merry-wives-of-windsor  
william-shakespeare/othello  
william-shakespeare/king-lear  
william-shakespeare/macbeth  
william-shakespeare/the-tempest  
miguel-de-cervantes-saavedra/don-quixote/john-ormsby  
john-milton/paradise-lost  
jonathan-swift/gullivers-travels  
laurence-sterne/the-life-and-opinions-of-tristram-shandy-gentleman  
henry-fielding/the-history-of-tom-jones-a-foundling  
alexander-hamilton_john-jay_james-madison/the-federalist-papers  
john-stuart-mill/on-liberty  
herman-melville/moby-dick  
charles-darwin/the-origin-of-species  
karl-marx_friedrich-engels/the-communist-manifesto/samuel-moore  
leo-tolstoy/war-and-peace/louise-maude_aylmer-maude  
fyodor-dostoevsky/the-brothers-karamazov/constance-garnett  
voltaire/candide/the-modern-library  
friedrich-nietzsche/beyond-good-and-evil/helen-zimmern  
jane-austen/emma  
george-eliot/middlemarch  
mark-twain/the-adventures-of-huckleberry-finn  
henrik-ibsen/a-dolls-house/r-farquharson-sharp  
henrik-ibsen/hedda-gabler/edmund-gosse_william-archer  
bertrand-russell/the-problems-of-philosophy  
joseph-conrad/heart-of-darkness  
luigi-pirandello/six-characters-in-search-of-an-author/edward-storer  
james-joyce/a-portrait-of-the-artist-as-a-young-man  
t-s-eliot/poetry  
f-scott-fitzgerald/the-great-gatsby

### CODE REVIEW

**Comment by acabal** [comment]
OK, but if we're going to do that then we should put together a spreadsheet for the items in that collection we don't have at SE yet. Not all of them would qualify, for example Treatise on Light, and others would go in an omnibus so some consideration is required. Can you work on that?

**Comment by acabal** [comment]
Also, `<meta>` cannot have children so you have to delete `<i>`.

**Comment by bentley** [comment]
Dropped `<i>`.

I’ll work on the spreadsheet before I make any more pull requests.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
